// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiTracNghiem.Data;

#nullable disable

namespace LapTrinhWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527063933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChuDeId")
                        .HasColumnType("int");

                    b.Property<string>("DapAnA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuDeId");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("ChuDe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuDeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("TenDeThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiMo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChuDeId");

                    b.ToTable("DeThis");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeThiId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeThiId");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.ChiTietLamBai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<string>("DapAnChon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DungHaySai")
                        .HasColumnType("bit");

                    b.Property<int>("LichSuLamBaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("LichSuLamBaiId");

                    b.ToTable("ChiTietLamBais");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.LichSuLamBai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeThiId")
                        .HasColumnType("int");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNopBai")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeThiId");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("LichSuLamBais");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.LienHe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("LienHes");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiKhoa")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("CauHoi", b =>
                {
                    b.HasOne("ChuDe", "ChuDe")
                        .WithMany("CacCauHoi")
                        .HasForeignKey("ChuDeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("DeThi", b =>
                {
                    b.HasOne("ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("ChuDeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.BinhLuan", b =>
                {
                    b.HasOne("DeThi", "DeThi")
                        .WithMany()
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThiTracNghiem.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TenTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeThi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.ChiTietLamBai", b =>
                {
                    b.HasOne("CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThiTracNghiem.Models.LichSuLamBai", "LichSuLamBai")
                        .WithMany("ChiTietLamBais")
                        .HasForeignKey("LichSuLamBaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("LichSuLamBai");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.LichSuLamBai", b =>
                {
                    b.HasOne("DeThi", "DeThi")
                        .WithMany()
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThiTracNghiem.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TenTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeThi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.LienHe", b =>
                {
                    b.HasOne("ThiTracNghiem.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TenTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ChuDe", b =>
                {
                    b.Navigation("CacCauHoi");
                });

            modelBuilder.Entity("ThiTracNghiem.Models.LichSuLamBai", b =>
                {
                    b.Navigation("ChiTietLamBais");
                });
#pragma warning restore 612, 618
        }
    }
}
